### PR TITLE
[Serialization] Fix device type when map_location is None

### PR DESCRIPTION
**Pull request by Wauplin**
## Context: just a PR to fix code quality CI (type error)

---

## Summary

`make quality` fails on `main` with a `ty` error:

```
src/huggingface_hub/serialization/_torch.py:788: error[invalid-argument-type]
Argument to function `load_file` is incorrect: Expected `str | int`, found `(str & ~Literal["meta"]) | None`
```

- `_load_safetensors_file` passes `map_location` to `safetensors.torch.load_file`, which expects `str | int`. When `map_location` is `None` (the default), `None` was passed.
- It was hidden behind `# type: ignore[arg-type]`. `mypy` honors that comment, `ty` does not, so only `ty` reports it.
- Fix: when `map_location` is `None`, use `"cpu"`. This is already what `load_file` falls back to, so nothing changes at runtime. The `type: ignore` is no longer needed.

Introduced in #4877. Found while triaging community issues, so it is in its own PR.

## Checks

`ty check src` and `mypy src` are both clean. `make quality` now passes fully.

Behaviour is identical for every input (verified by hand, the meta warning still fires):

| `map_location` | before | after |
|---|---|---|
| `None` | cpu | cpu |
| `"cpu"` | cpu | cpu |
| `torch.device("cpu")` | cpu | cpu |
| `"meta"` | cpu + warning | cpu + warning |
| `torch.device("meta")` | cpu + warning | cpu + warning |

`pytest tests/test_serialization.py` — 76 passed.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

---

> [!NOTE]
> **Low Risk**
> Typing-only clarification of existing CPU default for safetensors loads; no intended behavior change.
> 
> **Overview**
> Fixes a **static typing** issue in `_load_safetensors_file` where `map_location=None` could leave `device` as `None` and violate `safetensors.torch.load_file`'s `str | int` parameter (surfacing under `ty`, not `mypy`).
> 
> **`_load_safetensors_file`** now resolves `device` explicitly: default **`"cpu"`** when `map_location` is omitted, otherwise normalize `torch.device` / string inputs to a string before the existing **meta → cpu** fallback. The **`# type: ignore[arg-type]`** on `load_file` is removed.
> 
> Runtime behavior is unchanged—`None` already implied CPU in safetensors.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit a0c367f758690b305290294ce0fda97f57c51f4c. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Review by Wauplin — COMMENTED** [review]
✔️
