### ISSUE TITLE
notebook_login errors out after passing token in main branch

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/huggingface_hub#1072]
### Describe the bug

I installed main branch of huggingface_hub because I needed to use [dataset conversion tool](https://github.com/nateraw/huggingface-datasets-converter) where you can see `huggingface_hub` main branch in [requirements.txt](https://github.com/nateraw/huggingface-datasets-converter/blob/main/requirements.txt). The `notebook_login` errors out with logs below. This doesn't happen when I update last version of the library.

### Reproduction

You can try [this notebook](https://colab.research.google.com/drive/1XtfKYiQdxhQLpjLylpaftOHfrW89DbRs#scrollTo=rqjM6JlnGM8g). I tried only installing github repository itself and calling notebook_login and was able to reproduce it.

### Logs

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/huggingface_hub/commands/user.py in login_token_event(t)
    308         token_widget.value = ""
    309         clear_output()
--> 310         _login(token=token)
    311 
    312     token_finish_button.on_click(login_token_event)

TypeError: _login() missing 1 required positional argument: 'hf_api'
```

### System Info
(Below is tip of main branch)
```shell
huggingface-hub @ git+https://github.com/huggingface/huggingface_hub@3a59bf13f1ef50b2e7e9ac8362f5984ac288eb33
```

**Comment by Wauplin** [comment]
Hi @merveenoyan , thanks for reporting ! This regression has been introduced by https://github.com/huggingface/huggingface_hub/pull/1064. I fixed it here: https://github.com/huggingface/huggingface_hub/pull/1073. Sorry for that but very happy you noticed it before any release :D

**Comment by Wauplin** [comment]
In the meantime, you can pip install from `26819c73a47e56a53a2e047d540c0c456d31d70c`

**Comment by merveenoyan** [comment]
@Wauplin the last release works just fine, it's just the tool I mentioned in the issue is using main branch and that was my initial problem. If I revert to latest release the tool just won't work, that's why I didn't want to use that branch.

**Comment by Wauplin** [comment]
MErged :)

**Comment by nateraw** [comment]
@merveenoyan Did installing the latest release solve the problem for you while using the datasets converter? (v0.10.0rc0)

It did not solve the problem for me, I think, which is concerning.

**Comment by Wauplin** [comment]
@nateraw I haven't used the datasets converter tool but here is a simple [colab](https://colab.research.google.com/drive/1gaRnaUWarJuKzZcRojurgtV-XCiu2HUN?usp=sharing) where it works for me. Could you check `huggingface_hub` is correctly installed ? 

```
pip uninstall huggingface_hub
pip install huggingface_hub==0.10.0rc0
```

**Comment by osanseviero** [comment]
The login does work for me when installing from head

**Comment by nateraw** [comment]
The issue was fixed with [this PR](https://github.com/huggingface/huggingface_hub/pull/1084) I believe. Thanks all!!
